/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package graphql.client

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
    }
}
